name: Generate pacman animation

on:
  schedule: # Esegue ogni 12 ore
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Crea la cartella 'dist' prima, così l'azione sa dove salvare il file.
      #- name: Create dist directory
      #  run: mkdir -p dist

      # Step 2: Genera il file SVG di Pacman e salvalo direttamente dentro 'dist'.
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: and734
          file_name: dist/pacman-contribution-graph.svg # <-- MODIFICA CHIAVE: diciamo dove salvare il file

      # Step 3: Invia il contenuto della cartella 'dist' al branch 'output'.
      - name: Push pacman svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          keep_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
