name: generate pacman game
on:
  schedule:
    # Esegue automaticamente ogni 24 ore
    - cron: "0 */24 * * *"
  workflow_dispatch: # Permette l'avvio manuale
  push: # Si avvia ad ogni push sul branch main
    branches:
      - main
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: and734
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
